easy_admin:
    site_name: '<img src="/images/logoOclockCommunity.svg">'
    design:
      brand_color: '#0bad93'
      assets:
        favicon: '/images/oclock-fav.png'
    entities:
        # List the entity class name you want to manage
        Membres:
          class: App\Entity\AppUser
        Competences:
          class: App\Entity\Competence
        Images:
          class: App\Entity\Image
        Statuts_professionnels:
          class: App\Entity\ProfessionalStatus
        Projets:
          class: App\Entity\Project
        Promotions:
          class: App\Entity\Promotion
        Specialisation:
          class: App\Entity\Specialisation
        Roles:
          class: App\Entity\Role