easy_admin:
    site_name: '<img src="/img/logoOclockCommunity.svg">'
    design:
      form_theme: 'vertical'
      brand_color: '#194d61'
      assets:
        favicon: '/img/oclock-fav.png'
      menu:
         - { entity: 'Membres', icon: 'user' }
         - { entity: 'Promotions', icon: 'tasks' }
         - { entity: 'Specialisation', icon: 'list', label: 'Spécialisations'  }
         - { entity: 'Competences', icon: 'tags', label: 'Compétences' }
         - { entity: 'Statuts_professionnels', icon: 'briefcase', label: 'Statuts professionnels' }
         - { entity: 'Projets', icon: 'book' }
         - { entity: 'Images', icon: 'image', label: 'Images des projets' }
         - { entity: 'Roles', icon: 'cog', label: 'Rôles' }
         - { label: 'Retour à la page gestion', url: '/gestion', rel: 'index' }
         - { label: 'Retour vers le site', url: 'http://www.o-community.fr' }
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd-m-Y'
    entities:
            # List the entity class name you want to manage
        Membres:
            class: App\Entity\AppUser
            label: 'Membres'
            list:
                title: "Liste des étudiants"
                fields:
                  - id
                  - firstname
                  - lastname
                  - { property: 'contentUrl', type: 'image', base_path: '/img/profils/' }
                  - email
                  - birthdate
                  - Phone number
                  - role
                  - isActive
            show:
                fields:
                  - id
                  - firstname
                  - lastname
                  - { property: 'birthdate', type: 'birthday', label: 'birthdate', type_options: { format: 'dd-MM-yyyy'}}
                  - { property: 'contentUrl', type: 'image', base_path: '/img/profils/' }
                  - email
                  - city
                  - zipcode
                  - phone_number
                  - birthdate
                  - Phone number
                  - link_linkedin
                  - link_github
                  - link_personal
                  - role
                  - isActive
            form:
              fields:
                  - { type: 'tab' , label: 'Informations personnelles', icon: 'user' }
                  - lastname
                  - firstname
                  - { property: 'birthdate', type: 'birthday', label: 'birthdate', type_options: { format: 'dd-MM-yyyy'}}
                  - { property: 'file', type: 'vich_image' }
                  - { type: 'tab' , label: 'Informations de localisation', icon: 'home' }
                  - city
                  - zipcode
                  - { type: 'tab', label: 'Contacts', icon: 'envelope-o' }
                  - email
                  - phone_number
                  - { type: 'tab', label: 'Liens Github,linkedin et personnel', icon: 'link' }
                  - link_linkedin
                  - link_github
                  - link_personal
                  - { type: 'tab', label: 'Role', icon: 'link' }
                  - role                  

        Competences:
            class: App\Entity\Competence
            label: 'Competences'
            list:
                title: "Liste des compétences"
        Images:
            class: App\Entity\Image
            label: 'Images'
            list:
                title: "Liste des Images"
                fields:
                  - 'id'  
                  - { property: 'contentUrl', type: 'image', base_path: '/img/projects/' } 
                  - 'isHero'
                  - 'Project'
            show:
                fields:
                  - 'id'
                  - { property: 'contentUrl', type: 'image', base_path: '/img/projects/' } 
                  - 'isHero'
                  - 'updatedAt'
                  - 'Project'
            form:
                fields:
                  - { property: 'file', type: 'vich_image' }
                  - 'isHero'
        Statuts_professionnels:
            class: App\Entity\ProfessionalStatus
            label: 'Statuts_professionnels'
            list:
                title: "Liste des statuts professionnels"
        Projets:
            class: App\Entity\Project
            label: 'Projets'
            list:
                title: "Liste des projets"

        Promotions:
            class: App\Entity\Promotion
            label: 'Promotions'
            list:
                title: "Liste des promotions"
            form:
              fields:
                  - id
                  - Name
                  - { property: 'StartDate', type: 'datetime', label: 'StartDate' }
                  - { property: 'EndDate', type: 'datetime', label: 'EndDate' }
        Specialisation:
            class: App\Entity\Specialisation
            label: 'Spécialisation'
            list:
                title: "Liste des spécialisation"
        Roles:
            class: App\Entity\Role
            label: 'Roles'
            list:
                title: "Liste des roles"
    list:
        actions:
            - { name: 'show', icon: 'search', label: 'Voir', title: 'Search' }
            - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Edit' }
            - { name: 'delete', icon: 'trash', label: 'Supprimer', title: 'Edit' }