security:
    encoders:
        App\Entity\AppUser:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\AppUser
                property: email


    firewalls:

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        # api:
        #     pattern:   ^/
        #     stateless: true
        #     guard:
        #         authenticators:
        #             - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_COMMUNITY_ADMIN: ROLE_COMMUNITY_USER