security:
    encoders:
        App\Entity\AppUser:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\AppUser
                property: email


    firewalls:
        login_backend:
            pattern:   ^/app_login
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\AppUserAuthenticator
            logout:
                path: app_logout
                target: admin_index
            context: backend

        logout_backend:
            pattern:   ^/logout
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\AppUserAuthenticator
            logout:
                path: app_logout
                target: 'http://o-community.fr'
            context: backend

        admin:
            pattern:   ^/admin
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\AppUserAuthenticator
            logout:
                path: app_logout
                target: admin_index
            context: backend

        gestion:
            pattern:   ^/gestion
            anonymous: true
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\AppUserAuthenticator
            logout:
                path: app_logout
                target: admin_index
            context: backend

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            context: api


        api:
            pattern:   ^/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            context: api

    access_control:
        - { path: ^/admin, roles: ROLE_COMMUNITY_SUPERADMIN }
        - { path: ^/gestion, roles: ROLE_COMMUNITY_ADMIN }
        - { path: ^/app_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_COMMUNITY_SUPERADMIN: ROLE_COMMUNITY_ADMIN
        ROLE_COMMUNITY_ADMIN: ROLE_COMMUNITY_USER