vich_uploader:
    db_driver: orm

    mappings:
        profil_pictures:
           uri_prefix: /images/profils
           upload_destination: '%kernel.project_dir%/public/images/profils'
        project_pictures:
           uri_prefix: /images/projects
           upload_destination: '%kernel.project_dir%/public/images/projects'