vich_uploader:
    db_driver: orm

    mappings:
        profil_pictures:
           uri_prefix: /img/profils
           upload_destination: '%kernel.project_dir%/public/img/profils'

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
           namer: Vich\UploaderBundle\Naming\UniqidNamer

        project_pictures:
           uri_prefix: /img/projects
           upload_destination: '%kernel.project_dir%/public/img/projects'

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
           namer: Vich\UploaderBundle\Naming\UniqidNamer